### ISSUE TITLE
password field on meter place

### ISSUE THREAD

**Issue by area73** [equinusocio/native-elements#131]
I don't know if this is really a bug, but I see on the https://native-elements.stackblitz.io/ page that under METER heading you have a password input field , which I think it doesn't belong there

**Comment by equinusocio** [comment]
Hi, you see the small meter elements below the password field. The meter element measure the strength
 of a value based on specified values. Don't you see the meter elements below the field?

PS: Right now the password field and the meters are unlinked.

**Comment by area73** [comment]
Yes I show those 3 little bars and I play a little bit with them. I realize that they change colors depending on the value  😄 , but since input field is not attach to them it looks to me that it was an error.
So if that was your intention then the question is more philosophical. Do you want to show  in this page just components (isolated components) , or on the other hand do you want to show also compositions ?, so if the answer is the second one , maybe you can add a section for composition or letting to know the user that there is a composition ...

**Comment by equinusocio** [comment]
Yeah, make sense. Since this project is in its early development phase, i just put thing togheter, but i think i can remove the password field and just put standalone elements. The details gruop also combine multiple details but i think it's a different case.
